### PR TITLE
checklistValue parsed on-demand instead during compile phase

### PR DESCRIPTION
**Pull request by wjmazza**
If the value for `checklist-value` changes after compilation, the directive does not reflect these changes. By moving the "value" definition into the watcher and "setChecked" functions, we always get the latest value.

I originally created this to work with Angular Material's md-virtual-repeat and md-checkbox directives, but it seems it may also resolve/be the same as PR #103 but without the merge conflicts.

### CODE REVIEW

**Comment by beradrian** [comment]
Great! I will merge this. Could you also write a test case for this?

**Comment by wjmazza** [comment]
Will do. Please give me a day to figure out how to simulate the situation without angular-material and then write the tests

**Comment by beradrian** [comment]
Thanks! In the readme there's a section called "How to add a new test case" to make your life easier. :)

**Comment by wjmazza** [comment]
Tests have been added. Branch commits squashed/rebased.

**Comment by beradrian** [comment]
I merged your PR. You'll have to wait for a few days for the release. Thanks a lot!

**Pull request merged**
