### PR TITLE
Implement checklist-max-length

### PR DESCRIPTION
**Pull request by mittalabhas1**
Passing the checklist-max-length attribute allows to check only a maximum no. of checkboxes. Use case is quite clear.

### CODE REVIEW

**Comment by beradrian** [comment]
Your code doesn't work if you also specify the `ng-model` supported starting with version 0.3.0.
What happens if you specify a different max-length for two different checkboxes with the same `checklist-model` behind? Why not using the usual `maxlength` attribute?

**Comment by frandieguez** [comment]
Any update on this? We are facing the same problem and this would be really helpful to get things merged.

**Comment by beradrian** [comment]
I explained the issue here #15.

I think the best way to tackle this will be to implement checklist-minlength and checklist-maxlength. But what should happen, when you specify different values on different checkboxes bound to the same checklist-model?

As an example

<input type="checkbox" checklist-model="selected" checklist-minlength="1" value="a"/>
<input type="checkbox" checklist-model="selected" checklist-minlength="2" value="b"/>

I would tend to go for the simpler solution and do the validation using the value specified on the checkbox that is just clicked. But this could tend to be confusing.

Before implementing it I was waiting feedback from users.

**Comment by darrenshrwd** [comment]
Why not take the highest of those specified ...or even throw an error as surely it is human error if you have specified a different value on different check boxes?

**Comment by mittalabhas1** [comment]
Sorry for absconding. Will do that soon.

On Wednesday 11 November 2015, Darren Sherwood <notifications@github.com>
wrote:

> Why not take the highest of those specified ...or even throw an error as
> surely it is human error if you have specified a different value on
> different check boxes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vitalets/checklist-model/pull/79#issuecomment-155656228>
> .
>


-- 

*Abhas Mittal*
+91-8266063709

**Comment by beradrian** [comment]
@mittalabhas1, sorry for asking - do what soon?

**Comment by beradrian** [comment]
I implemented this with checklist-before-change in version 0.8.0. See #15.

**Pull request closed without merging**
