### PR TITLE
Add support for dynamic checklist options.

### PR DESCRIPTION
**Pull request by blingerson**
This adds support for dynamically change values. For example I was using checklist model where the objects in the ng repeat were { l : 'label', v : 'value' } and the checklist-value was opt.v.

In the user interface the label and value were input fields that the user could modify. This change updates the checklist-model with any user inputed values after the initial compile phase.

### CODE REVIEW

**Comment by beradrian** [comment]
Could you please add a test case for this as well? Thanks!

**Comment by beradrian** [comment]
Meantime I implemented checklist-before-change. Could you please resolve the conflict and add a new test case so I can merge it? Thanks!

**Comment by beradrian** [comment]
Could you please resolve the conflict? I will try to add the test case myself.

**Comment by beradrian** [comment]
I will close this PR, as it was solved by PR 111, with no conflicts and test case.

**Comment by blingerson** [comment]
Thanks, sorry I didn't get a chance to respond sooner.

**Pull request closed without merging**
